name: DeluxeCrafting
main: me.sedattr.deluxecrafting.DeluxeCrafting

author: SedatTR
version: 1.0

description: The best, cheap, advanced, fully customizable crafting plugin!
website: https://discord.gg/nchk86TKMT